### ISSUE TITLE
There is now way to disconnect profile

### ISSUE THREAD

**Issue by ottodevs** [Hackerthonweb3/proof-of-networking#31]
Previously the app has the ability to disconnect the user, this was removed, I think it is important to allow the user to easily disconnect from the app, and manage orbis disconnect as well.

**Comment by asyaasha** [comment]
makes sense, removed when was trying to troubleshot the wagmi issue, will be adding it back

**Comment by asyaasha** [comment]
closing: it should be possible to disconnect now after https://github.com/Hackerthonweb3/proof-of-networking/pull/39
